In [1]:
import numpy as np

In [2]:
print('Testing Numpy')

Testing Numpy


In [3]:
np_array = np.array([1, 3, 4, 7, 10], np.int32)

In [4]:
print(np_array)

[ 1  3  4  7 10]


In [5]:
np_array.shape # for getting info of array, returns value in a tupple

(5,)

In [7]:
np_array[0] = 11

In [8]:
np_array

array([11,  3,  4,  7, 10])

# Ways to create numpy array
**Conversion from other python structures like lists or tuples**
-----------------------------------------------------------------
**Intrinsic numpy array creation objects (arrange, ones, zeros, etc.)**
-----------------------------------------------------------------
**Reading arrays from disks, either from standard or custom formats**
-----------------------------------------------------------------
**Creating Arrays from raw bytes through the use of strings or buffers**
-----------------------------------------------------------------
**Use of special library functions like random**
-----------------------------------------------------------------

# Conversion from other Python structures

In [9]:
listArray = np.array([[1, 2, 3], [4,  5, 6], [7, 8, 9]])

In [10]:
listArray.dtype; listArray.shape; listArray.size

9

In [11]:
print(f'{listArray.dtype}; {listArray.shape}; {listArray.size}')

int32; (3, 3); 9


In [12]:
np.array({33, 55, 77, 88}) # this will create an object type which is not efficient

array({88, 33, 77, 55}, dtype=object)

# Intrinsic Numpy Array

In [13]:
zeros = np.zeros((2, 5)) # creates a numpy array of given size (row X column) filled with zeros

In [14]:
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
rng = np.arange(15) # returns a numpy array within the given range

In [16]:
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [17]:
lsp = np.linspace(1, 50, 100) # gives equally linear elements from one range to another with in the size specified in third argument

In [18]:
print(lsp)

[ 1.          1.49494949  1.98989899  2.48484848  2.97979798  3.47474747
  3.96969697  4.46464646  4.95959596  5.45454545  5.94949495  6.44444444
  6.93939394  7.43434343  7.92929293  8.42424242  8.91919192  9.41414141
  9.90909091 10.4040404  10.8989899  11.39393939 11.88888889 12.38383838
 12.87878788 13.37373737 13.86868687 14.36363636 14.85858586 15.35353535
 15.84848485 16.34343434 16.83838384 17.33333333 17.82828283 18.32323232
 18.81818182 19.31313131 19.80808081 20.3030303  20.7979798  21.29292929
 21.78787879 22.28282828 22.77777778 23.27272727 23.76767677 24.26262626
 24.75757576 25.25252525 25.74747475 26.24242424 26.73737374 27.23232323
 27.72727273 28.22222222 28.71717172 29.21212121 29.70707071 30.2020202
 30.6969697  31.19191919 31.68686869 32.18181818 32.67676768 33.17171717
 33.66666667 34.16161616 34.65656566 35.15151515 35.64646465 36.14141414
 36.63636364 37.13131313 37.62626263 38.12121212 38.61616162 39.11111111
 39.60606061 40.1010101  40.5959596  41.09090909 41.

In [19]:
lspc = np.linspace(1, 10, 2); print(lspc)

[ 1. 10.]


In [21]:
emp = np.empty((5, 3)) # returns an array with random values of the specified rows and columns

In [22]:
print(emp)

[[0.000000e+000 0.000000e+000 0.000000e+000]
 [0.000000e+000 0.000000e+000 0.000000e+000]
 [0.000000e+000 0.000000e+000 0.000000e+000]
 [0.000000e+000 0.000000e+000 0.000000e+000]
 [0.000000e+000 0.000000e+000 3.496989e-317]]


In [23]:
emp_like = np.empty_like(lsp); print(emp_like) # this will return an array that has same dimensions as the given array

[ 1.          1.49494949  1.98989899  2.48484848  2.97979798  3.47474747
  3.96969697  4.46464646  4.95959596  5.45454545  5.94949495  6.44444444
  6.93939394  7.43434343  7.92929293  8.42424242  8.91919192  9.41414141
  9.90909091 10.4040404  10.8989899  11.39393939 11.88888889 12.38383838
 12.87878788 13.37373737 13.86868687 14.36363636 14.85858586 15.35353535
 15.84848485 16.34343434 16.83838384 17.33333333 17.82828283 18.32323232
 18.81818182 19.31313131 19.80808081 20.3030303  20.7979798  21.29292929
 21.78787879 22.28282828 22.77777778 23.27272727 23.76767677 24.26262626
 24.75757576 25.25252525 25.74747475 26.24242424 26.73737374 27.23232323
 27.72727273 28.22222222 28.71717172 29.21212121 29.70707071 30.2020202
 30.6969697  31.19191919 31.68686869 32.18181818 32.67676768 33.17171717
 33.66666667 34.16161616 34.65656566 35.15151515 35.64646465 36.14141414
 36.63636364 37.13131313 37.62626263 38.12121212 38.61616162 39.11111111
 39.60606061 40.1010101  40.5959596  41.09090909 41.

In [24]:
identity = np.identity(5) # will return an identity matrix of given size

In [25]:
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
arr = np.arange(10); arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr.reshape(5, 2); arr.shape # will reshape the given array if possible

(10,)

In [29]:
arr.ravel() # this will convert an array to linear 1D Array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr.shape

(10,)

In [32]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Understanding Axis in numpy array

In [35]:
axis = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 1, 0]
])

In [36]:
axis.sum(axis=0) # will return the sum of all elements in column wise order

array([12,  8,  9])

In [37]:
axis.sum(axis=1) # will return sum of elements in row wise order

array([ 6, 15,  8])

In [38]:
axis.T # will transpose the 2D array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [39]:
new_arr = np.array(axis)

In [40]:
print(new_arr.flat) # will convert an array into flat structure

In [43]:
l1 = [print(i) for i in new_arr.flat]

1
2
3
4
5
6
7
1
0


In [44]:
axis.ndim # returns the dimensions of a numpy array

2

In [45]:
axis.size # returns the size of numpy array in terms of number of elements contained in the array

9

In [46]:
axis.nbytes # returns total bytes consumed by the elements of a numpy array

36

In [50]:
one = np.array([100, 13, 4, 1, 7])
print(one.argmax()) # returns the index of element that is largest in the numpy array

0


In [51]:
print(one.argmin()) # returns the index of element that is smallest

3


In [53]:
one.argsort() # sorts the numpy array in descending order

array([3, 2, 4, 1, 0], dtype=int64)

In [55]:
print(f'{axis.argmin()} {axis.argmax()}') # will first convert the 2d numpy array into a flat array and then return the indexes

8 6


In [56]:
print(f'{axis.argmax(axis= 1)} {axis.argmax(axis= 1)}') # for column wise and row wise

[2 2 0] [2 2 0]


In [57]:
print(axis)

[[1 2 3]
 [4 5 6]
 [7 1 0]]


In [58]:
axis.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

# Mathematical functions with numpy array

In [60]:
arr1 = np.array([
    [1, 2],
    [3, 4]
])
arr2 = np.array ( [
    [5, 6],
    [7, 8]
])
arr1 + arr2 # will add the values of both arrays

array([[ 6,  8],
       [10, 12]])

In [61]:
[
    [1, 2],
    [3, 4]
] + [
    [5, 6],
    [7, 8]
]

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [63]:
print(arr1)
print(arr2)
arr1*arr2

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[ 5, 12],
       [21, 32]])

In [64]:
np.sqrt(arr1) # returns the element wise square root of all elements

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [67]:
print(f'{arr1.sum()} {arr1.min()} {arr1.max()}')

10 1 4


In [68]:
np.where(arr1>3) # return the indexes of elements that are greater than given values

(array([1], dtype=int64), array([1], dtype=int64))

In [69]:
np.count_nonzero(arr1) # returns count of all non zero elements

4

In [70]:
np.nonzero(arr1) # returns indexes of all non zero elements

(array([0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1], dtype=int64))

In [71]:
import sys

In [73]:
py_arr = [1, 3, 5, 7]
np_arr = np.array(py_arr)
print(sys.getsizeof(1) * len(py_arr))
print(np_arr.itemsize * np_array.size)

112
20


In [74]:
np_arr.tolist() # converts a numpy array to a python list

[1, 3, 5, 7]